### ISSUE TITLE
Failiure in generating BBEs for the website

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-release#2419]
**Description:**

Getting following error while generating the BBEs for the website using distribution 2201.6.x branch.

```
Processing BBE : Configure logging
EEXIST: file already exists, mkdir 'swan-lake/by-example/logging-configuration'
```

**Comment by praneesha** [comment]
This is because we have 2 BBEs with the same URL under both the `log`[1] and `EDI`[2] titles as shown below.

<img width="1728" alt="Screenshot 2023-06-02 at 05 01 33" src="https://github.com/ballerina-platform/ballerina-release/assets/11707273/db1b31b2-6c31-498c-8ed8-5d596b343986">

Renaming the `name` and `URL` of [2] as follows should be able to rectify this.

[1] https://github.com/ballerina-platform/ballerina-distribution/blob/f3bc22d7ff47d4ad5d9deb786b1a043a44202c8c/examples/index.json#L4030
[2] https://github.com/ballerina-platform/ballerina-distribution/blob/f3bc22d7ff47d4ad5d9deb786b1a043a44202c8c/examples/index.json#L4083

**Comment by praneesha** [comment]
As we don't have a configure logging BBE for EDI, removing it the entry of it from the `index.json` will rectify this. This is done in https://github.com/ballerina-platform/ballerina-distribution/pull/4523.

**Comment by SasinduDilshara** [comment]
> As we don't have a configure logging BBE for EDI, removing it the entry of it from the `index.json` will rectify this. This is done in [ballerina-platform/ballerina-distribution#4523](https://github.com/ballerina-platform/ballerina-distribution/pull/4523).

Close the issue because of this PR
