### ISSUE TITLE
Update 9 RC1 build fails due to project API test failure

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-release#2652]
log - https://github.com/ballerina-platform/ballerina-distribution/actions/runs/8641129330/job/23691215084

**Comment by gayaldassanayake** [comment]
These original failures were due to the unavailability of Asgardio during holidays, which caused dev-central to be unresponsive. However, there were some additional failures observed once that was observed due to assertion failures. This was due to the addition of hash validation for bal push. The tests have been modified to avoid this.
